environment:
  REGION: ${REGION}
  BUCKET: ${BUCKET}
  SPACES_KEY: ${SPACES_KEY}
  SPACES_SECRET: ${SPACES_SECRET}
packages:
  - name: feed
    functions:
      - name: viewmodel
        runtime: go:1.20
        web: true
