alerts:
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
functions:
  - name: wedding-api
    github:
      branch: main
      deploy_on_push: true
      repo: aelhage/wedding
    source_dir: /
    envs:
      - key: REGION
        scope: RUN_AND_BUILD_TIME
      - key: BUCKET
        scope: RUN_AND_BUILD_TIME
      - key: SPACES_KEY
        scope: RUN_AND_BUILD_TIME
      - key: SPACES_SECRET
        type: SECRET
        scope: RUN_AND_BUILD_TIME
ingress:
  rules:
    - component:
        name: wedding-api
      match:
        path:
          prefix: /api
    - component:
        name: wedding-ui
      match:
        path:
          prefix: /
name: wedding-app
region: nyc
static_sites:
  - name: wedding-ui
    github:
      branch: main
      deploy_on_push: true
      repo: aelhage/wedding
    source_dir: /web
    output_dir: /build
    build_command: npm run build
    environment_slug: node-js
    envs:
      - key: PUBLIC_BASE_API_URL
        scope: BUILD_TIME
        value: ${wedding-api.PUBLIC_URL}
