alerts:
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
functions:
  - github:
      branch: main
      deploy_on_push: true
      repo: aelhage/wedding
    name: wedding-api
    source_dir: /
ingress:
  rules:
    - component:
        name: wedding-api
      match:
        path:
          prefix: /api
    - component:
        name: wedding-ui
      match:
        path:
          prefix: /
name: wedding-app
region: nyc
static_sites:
  - github:
      branch: main
      deploy_on_push: true
      repo: aelhage/wedding
    name: wedding-ui
    source_dir: /web
    output_dir: /build
    build_command: npm run build
    environment_slug: node-js
