spec:
  alerts:
    - rules: DEPLOYMENT_FAILED
    - rules: DOMAIN_FAILED
  functions:
    - github:
        branch: main
        deploy_on_push: true
        repo: aelhage/wedding
      name: feed-api
      routes:
        - path: /
      source_dir: /
  static_sites:
    - github:
        branch: main
        deploy_on_push: true
        repo: aelhage/wedding
      source_dir: /web
  name: feed
